### ISSUE TITLE
can't login :( sigh 

### ISSUE THREAD

**Issue by nightwing25** [carpedm20/LINE#100]
Login Failed
Traceback (most recent call last):
File "echobot.py", line 12, in 
for op in client.longPoll():
NameError: name 'client' is not defined

**Comment by anysz** [comment]
Your Line library didnt installed.
If youre on Windows:
Open cmd, `cd \[to-setup.py-path]`
Then type `setup.py install`

fyi:
I guess next error must be on the thrift library

**Comment by anysz** [comment]
#95 #96

**Comment by nightwing25** [comment]
just saw this but before a friend of mine told me its beacuse i didnt import client in the echobot.py
so i did what he said and got a new error also im using ubuntu.

Login Failed
Traceback (most recent call last):
  File "echobot.py", line 12, in <module>
    for op in client.longPoll():
AttributeError: 'module' object has no attribute 'longPoll'

**Comment by anysz** [comment]
you need debug each line code from console to know what going on.
`$ python`
`>> from line import LineClient, LineGroup, LineContact`
`>> client = LineClient("email", "pass")`

the next should be `Enter PinCode '[PIN_CODE]' to your mobile phone in 2 minutes`
if isnt, try to check thrift 0.9.3 and carpedm20 line library installed correctly by python

Ubuntu should be easier than Windows .-.

**Comment by RichoDS** [comment]
![untitled](https://cloud.githubusercontent.com/assets/29066224/26650070/1ea6c7b0-45fd-11e7-8e76-a6f374f4d0d4.png)


what's next?

**Comment by RichoDS** [comment]
![untitled](https://cloud.githubusercontent.com/assets/29066224/26650152/5fa106e0-45fd-11e7-9607-fe04b97b1ea9.png)


what's next??
