### ISSUE TITLE
global name 'app' is not defined

### ISSUE THREAD

**Issue by ObligatedUsername** [carpedm20/LINE#105]
Error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\line\client.py", line 88, in __init__
  File "C:\Python27\lib\site-packages\line-0.8.2-py2.7.egg\line\api.py", line 13
3, in login
NameError: global name 'app' is not defined

I'm pretty new to python, so if anyone could help, I'd really appreciate it

**Comment by anysz** [comment]
Did you run echobot.py?

**Comment by ObligatedUsername** [comment]
No, I didn't. Is that the cause of the error?

**Comment by anysz** [comment]
I recommend you to check by using python.
Try this.
> > `$ python`
> > `Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32`
> > `Type "help", "copyright", "credits" or "license" for more information.`
> > `>>> from line import LineClient, LineGroup, LineContact`
> > `>>> client = LineClient("email", "pass", com_name="LOG_KIT")`

if the code on the top doesnt get any error, that mean you successfully logged in.
Check if youre logged in by:
> > `>>> client.updateAuthToken()`

**Comment by ObligatedUsername** [comment]
now I'm getting bad protocol id 60, and I've installed thrift 0.9.3

**Comment by anysz** [comment]
Something wrong between your client and LINE server. Maybe try another subserv?

**Comment by Nilpo** [comment]
Do `pip uninstall line`. This will remove the installed version. Then set up the version in this repository.

    cd LINE
    python config.py
    python setup.py install
