### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by itayayuichiro** [carpedm20/LINE#114]
>>> from line import LineClient
>>> client = LineClient("ID", "pass")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 88, in __init__
    self.login()
  File "line/api.py", line 88, in login
    j = self._get_json(self.LINE_SESSION_LINE_URL)
  File "line/api.py", line 335, in _get_json
    return json.loads(self._session.get(url, headers=self._headers).text)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Nilpo** [comment]
Please see Issue #92 .
