### ISSUE TITLE
Account ID and password does not match', code=18)

### ISSUE THREAD

**Issue by anythingg** [carpedm20/LINE#116]
It lets me put in my email and password just fine. But when I try to put in my ID and password I get this error.

>>> client = LineClient("blah", "blahblah")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/line/client.py", line 88, in __init__
  File "build/bdist.linux-x86_64/egg/line/api.py", line 130, in login
  File "/home/jin/.local/lib/python2.7/site-packages/curve/CurveThrift.py", line 344, in loginWithIdentityCredentialForCertificate
    return self.recv_loginWithIdentityCredentialForCertificate()
  File "/home/jin/.local/lib/python2.7/site-packages/curve/CurveThrift.py", line 375, in recv_loginWithIdentityCredentialForCertificate
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='Account ID and password does not match', code=18)

**Comment by R-N** [comment]
Account ID, like, the one that starts with @? One that you made yourself in the Line app? I don't think you can use that

**Comment by anysz** [comment]
account id is mid i think.
id start with @ is for LINE@

**Comment by Nilpo** [comment]
You must log in with email and password.
