### ISSUE TITLE
got annoying eror :(

### ISSUE THREAD

**Issue by Nabouste** [carpedm20/LINE#117]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\line\client.py", line 88, in __init__
    self.login()
  File "C:\Python27\lib\site-packages\line\api.py", line 88, in login
    j = self._get_json(self.LINE_SESSION_LINE_URL)
  File "C:\Python27\lib\site-packages\line\api.py", line 335, in _get_json
    return json.loads(self._session.get(url, headers=self._headers).text)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

ive see and change and follow the instruction in [https://github.com/carpedm20/LINE/issues/92](url)
but nothing's change and still got an error

Appreciate someone's help.

**Comment by anysz** [comment]
its just pick the rsa key. so it looks like you can do get it without visiting :
    LINE_SESSION_LINE_URL  = LINE_DOMAIN + "/authct/v1/keys/line"
    LINE_SESSION_NAVER_URL = LINE_DOMAIN + "/authct/v1/keys/naver"

this might hint you:
i was found this on LINE ANDROID Thrift client 
info:
IdentityProvider.LINE = 1
IdentityProvider.UNKNOWN = 0
IdentityProvider.NAVER_KR = 2

`   RSA = LineAndroid.getRSAKeyInfo(1)`
`    message = (chr(len(RSA.sessionKey)) + RSA.sessionKey + chr(len(mail)) + mail + chr(len(passwd)) + passwd).encode('utf-8')`
`    pub_key = rsa.PublicKey(int(RSA.nvalue, 16), int(RSA.evalue, 16))`
`    crypto = rsa.encrypt(message, pub_key).encode('hex')`
`    result = self.client.loginWithIdentityCredentialForCertificate(1,rsakey.keynm, crypto,True,'127.0.0.1','Anysz',cert)`

**Comment by Nilpo** [comment]
@Nabouste The error you are seeing means that the Line Client is receiving an empty response from the API. There are several reasons that this could happen. Issue #92 addresses one reason. If you have already made the changes suggested in that issue, you may be running into another cause. Please post the relevant code so we can see what's happening. Also, please post the output from `thrift --version`.
