### ISSUE TITLE
[authToken login] Bad protocol id in the message : 60 

### ISSUE THREAD

**Issue by Mari2928** [carpedm20/LINE#118]
Does anyone know how to pass this issue? Got authToken, but cannot log on with this issue.

>>> from line import LineClient
>>> client = LineClient(authToken='****=')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\line\client.py", line 95, in __init__
    self.revision = self._getLastOpRevision()
  File "C:\Python27\lib\site-packages\line\api.py", line 317, in _getLastOpRevis
ion
    return self._client.getLastOpRevision()
  File "C:\Python27\lib\site-packages\curve\CurveThrift.py", line 512, in getLas
tOpRevision
    return self.recv_getLastOpRevision()
  File "C:\Python27\lib\site-packages\curve\CurveThrift.py", line 522, in recv_g
etLastOpRevision
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line
 315, in readMessageBegin
    'Bad protocol id in the message: %d' % proto_id)
thrift.protocol.TProtocol.TProtocolException: Bad protocol id in the message: 60

**Comment by SupraMKIV** [comment]
What fixed it for you?

**Comment by Mari2928** [comment]
1. $ pip install line
2. $ wget https://gist.github.com/windows98SE/b739038218b6fe4d423f/raw/5f68cf3d9a2a88576b739810a6bd6fcaa0c5e940/api.py.patch --no-check-certificate
$ patch api.py < api.py.patch

3. In api.py, change server URL to "https" from "http" .

**Comment by anysz** [comment]
Nice .-.
