### ISSUE TITLE
cant log in with auth token

### ISSUE THREAD

**Issue by anythingg** [carpedm20/LINE#119]
jin@jins-pc:~/LINE$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from line import LineClient, LineGroup, LineContact, LineRoom, LineMessage, LineBase
>>> client = LineClient("blah@gmail.com", "password", com_name="Blah", is_mac=False)
Enter PinCode '9609' to your mobile phone in 2 minutes
>>> authToken = client.authToken
>>> print authToken
EhRAc4R0G4okTvDNhIsa.cNJK/hGTeYoWLIw3l3YrkG.JLJtGDnWuR/ORu/VrcCAq9KdIb5Tjb9ZtCRq7ZhZFdt=
>>> client.updateAuthToken()
True
>>> print client.authToken
EhmgIMcAavJS6oN0mzOa.cNJK/hGTeYoWLIw3l3YrkG.k5vfgHMjMYRLTpMSrT5+S67ohqilY8/jmPAQw2tsVo4=
>>> client = LineClient(authToken=EhmgIMcAavJS6oN0mzOa.cNJK/hGTeYoWLIw3l3YrkG.k5vfgHMjMYRLTpMSrT5+S67ohqilY8/jmPAQw2tsVo4=)
  File "<stdin>", line 1
    client = LineClient(authToken=EhmgIMcAavJS6oN0mzOa.cNJK/hGTeYoWLIw3l3YrkG.k5vfgHMjMYRLTpMSrT5+S67ohqilY8/jmPAQw2tsVo4=)
                                                                                                                         ^
SyntaxError: invalid syntax
>>> client = LineClient(authToken='EhmgIMcAavJS6oN0mzOa.cNJK/hGTeYoWLIw3l3YrkG.k5vfgHMjMYRLTpMSrT5+S67ohqilY8/jmPAQw2tsVo4=')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 97, in __init__
    self.revision = self._getLastOpRevision()
  File "line/api.py", line 328, in _getLastOpRevision
    return self._client.getLastOpRevision()
  File "/home/jin/.local/lib/python2.7/site-packages/curve/CurveThrift.py", line 512, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/home/jin/.local/lib/python2.7/site-packages/curve/CurveThrift.py", line 534, in recv_getLastOpRevision
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='Authentication Failed.', code=1)

**Comment by anysz** [comment]
try login again

**Comment by anythingg** [comment]
I figured it out. I just had to type client.authToken to print the current auth token. For some reason what I was doing previously was just printing the old auth token.

**Comment by anysz** [comment]
Why u update authtoken? When u re login it will generator new one so u can remove it.

**Comment by fpitlok** [comment]
TalkException(parameterMap=None, reason='LOG_OUT', code=8)

I got this error,who can help ke solved this error
:pensive:

**Comment by zakariaastrada** [comment]
b/curve/LineService.py", line 9907, in recv_getLastOpRevision
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='Authentication Failed.', code=1)

help please -_-
