### ISSUE TITLE
KeyError: 'result'

### ISSUE THREAD

**Issue by fabrother** [carpedm20/LINE#122]
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
>>> from line import LineClient
>>> client = LineClient("ID", "PASSWOD")
Enter PinCode '4602' to your mobile phone in 2 minutes
{"result":{"verifier":"xtqa8rNEFkDTQEp0LA2Lw6NfWt2vVaJ7","authPhase":"QRCODE_VERIFIED","metadata":{}},"timestamp":"1499252728417"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/line/client.py", line 88, in __init__
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/line/api.py", line 132, in login
    self.verifier = j['result']['verifier']
KeyError: 'result'

How do I fix it ?

**Comment by anysz** [comment]
Does this solved?

**Comment by fabrother** [comment]
Thinks, It is fix, the reason is my adding code.
