### ISSUE TITLE
simplejson.scanner.JSONDecodeError

### ISSUE THREAD

**Issue by nininono** [carpedm20/LINE#125]
hello
i used of your API
but then i write 
```
$ pip install line --upgrade
$ python
>>> from line import LineClient, LineGroup, LineContact
>>> client = LineClient("myID", "myPASSWORD")
```
then i pressed Enter Key
i received this Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/line/client.py", line 88, in __init__
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/line/api.py", line 88, in login
    j = self._get_json(self.LINE_SESSION_NAVER_URL)
  File "/usr/local/lib/python2.7/dist-packages/line/api.py", line 335, in _get_json
    def post_content(self, url, data=None, files=None):
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

why???
please help me

i tested on ubuntu 16 and kali 2

thank you

**Comment by Nilpo** [comment]
Please look at the other issues. You most likely need to roll back the thrift version you have installed. See #90, #92, and #93.
