### ISSUE TITLE
Line update, what do we do now?

### ISSUE THREAD

**Issue by monhustla** [carpedm20/LINE#131]
Has anyone formulated a work around yet?

**Comment by anysz** [comment]
Me and some other does, cant expain here, its too dangerous

**Comment by scomma** [comment]
@anysz what's a good way to contact you?

**Comment by R-N** [comment]
api.py

0. Above __init__, set:
LINE_HTTP_IN_URL       = LINE_DOMAIN + "/P4"
LINE_HTTP_OUT_URL       = LINE_DOMAIN + "/S4"

1. comment out anything with _in (client_in, transport_in, etc)

2. in ready(self), change
self.transport = THttpClient(self.LINE_HTTP_URL)
to
self.transport = THttpClient(self.LINE_HTTP_IN_URL)

3. make a copy of self.transport = ...,, self.protocol = ..., self.client = ..., self.client.open() in ready(self), and add _out to em (transport_out, etc), then change:
self.transport_out = THttpClient(self.LINE_HTTP_IN_URL)
to
self.transport_out = THttpClient(self.LINE_HTTP_OUT_URL)

4. Make anything that should send notification use client_out instead (ex. sendMessage)

5. change tokenLogin(self) to just
def tokenLogin(self):
-----ready()

6. in login(self) change
self.transport = THttpClient(self.LINE_HTTP_URL)
to
if self.authToken is None:
----self.transport = THttpClient(self.LINE_HTTP_URL)
else:
----self.transport = THttpClient(self.LINE_HTTP_IN_URL)

Pardon the '-'s, I meant spaces.

**Comment by BloodySenpai** [comment]
@R-N Can you link me the actual code. This is confusing.

**Comment by anysz** [comment]
@R-N is explaining about how to login with authToken.

**Comment by BloodySenpai** [comment]
@anysz  I know this was never a problem before I'm wondering why he edited it

**Comment by BloodySenpai** [comment]
Stop being gay @anysz

**Comment by Juahmalem** [comment]
@anysz hey, I know you

**Comment by R-N** [comment]
Which part confuse you? 
Who edited what?

**Comment by zxchidden** [comment]
My bot can't login since yesterday, but before can. Has anyone can help?

**Comment by monhustla** [comment]
I know why @anysz can't show. Line is cracking down fast on any kind of fixes. We need to be careful what we put out there after finding a new fix.

**Comment by scomma** [comment]
Obviously we need to collaborate despite that, so maybe a closed discussion group?

**Comment by Mari2928** [comment]
@R-N May I ask you the code hint for your step# 4 ? >>Make POST requests (or just anything that should send notification) use client_out instead (ex. sendMessage)

**Comment by Mari2928** [comment]
Also, I get the error when the script runs your step 6.
`        if self.authToken is None:
            self.transport = THttpClient.THttpClient(self.LINE_HTTP_URL)
        else:
            self.transport = THttpClient.THttpClient(self.LINE_HTTP_IN_URL)`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\line\client.py", line 88, in __init__
    self.login()
  File "C:\Python27\lib\site-packages\line\api.py", line 130, in login
    if self.authToken is None:
  File "C:\Python27\lib\site-packages\curve\CurveThrift.py", line 344, in loginWithIdentityCredentialForCertificate
    return self.recv_loginWithIdentityCredentialForCertificate()
  File "C:\Python27\lib\site-packages\curve\CurveThrift.py", line 375, in recv_loginWithIdentityCredentialForCertificate
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='Internal error', code=20)

**Comment by Mari2928** [comment]
I found the tokens created before July 30 are still working fine with previous api.py.

**Comment by BloodySenpai** [comment]
Line made their move.

**Comment by ii64** [comment]
Anyone want to contact me just chat me.
<:)>

**Comment by R-N** [comment]
This afternoon my authToken expired. Not sure if Line 'did' it or it was just normal expiration. But then I get Internal Error code=20 when logging in with email. Maybe Line made their move just like @BloodySenpai  said. 

@Mari2928 In api.py, some method will send notification to user. For example, sendMessage, acceptGroupInvitation, inviteIntoGroup/Room, kickFromGroup, etc. Those should use S4 (_client_out) if you want them to send notification. I don't know if P4 worked for those too. TalkService worked but never send notification. 
Though now none works for me, lol.

**Comment by Mari2928** [comment]
@R-N I see. Thank you for the information. My token (issued one month ago) is still valid and works sending messages, but the tokens for my friends which were issued 2 days ago became invalid today. I hope there is any solution for going forward...

**Comment by R-N** [comment]
You're welcome.
By the way maybe we can just use both P4 and S4 in one CurveClient by providing P4 protocol for iprot and S4 protocol for oprot. Can't test tho.

**Comment by anythingg** [comment]
@R-N  I did what you said but i get this error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 88, in __init__
    self.login()
  File "line/api.py", line 123, in login
    if self.authToken is None:
AttributeError: 'LineClient' object has no attribute 'authToken'

**Comment by anythingg** [comment]
oh. never mind. I just noticed that you said after your authtoken expired you couldnt log in because of the new line update. I thought that was a work around you posted.

**Comment by alroysh** [comment]
@R-N can you upload your script on your github??

**Comment by R-N** [comment]
It doesnt even work right now

**Comment by Mari2928** [comment]
@alroysh: This line api is still working with the current version as of today. I can send messages as usual now. The problem is that we can't get a new token now. Some people tokens became invalid because maybe their desktop logins were automatically logged out while their line apps were being updated.I think we don't need to figure out how to login with token, but just need to find a way to get a new token.

**Comment by R-N** [comment]
I got it working but I can't tell how here. I'm quite certain it can be easily patched. My hint is to look at purple-line on altrepo. 

By the way, using HTTP_IN for iprot and HTTP_OUT for oprot on the same client doesnt work lole. Getting EOF ERROR.

By the way, it's actually possible to pool the CurveClients lol. That really speed things up for me.

**Comment by Mari2928** [comment]
@R-N Oh have you succeeded to get a new token after the line update?

**Comment by Ploiiz** [comment]
I have a problem too.
I try to edit api.py follow above comment,but I still login failed.
Could you please help to summary solution for solve issue about 'Internal error' and "'LineClient' object has no attribute 'authToken'"
Thank you for advised.

**Comment by mamesiba** [comment]
I can login now, could get a authToken

**Comment by Mari2928** [comment]
Still same Internal Error on mine. Have you logged in with LINE ID and password and then get a token?

**Comment by alroysh** [comment]
@mamesiba can you help me?

**Comment by alroysh** [comment]
@Mari2928 can you help me?
LINE ID : alroysh

**Comment by mamesiba** [comment]
@Mari2928 No,i'm QR code login

**Comment by alroysh** [comment]
@mamesiba please comment your ID LINE

**Comment by Mari2928** [comment]
@mamesiba-san How can I log in with QR code with this API? I haven't tried that way

**Comment by sol1456** [comment]
Hello every one.
I'm Japanese, so I can't speak fluent English.
But I also know a way of QR login and a countermeasure about this InternalError.
But there are no places where I share information about LINEAPI.
It isn't possible to speak about anything.
But as far as it's possible, I'd like to exchange information.

Don't you talk about LINEAPI by a group of LINE?

**Comment by kumarmanish511** [comment]
my line account was banned/blocked 
i can't chat to any one
what can i do for now 
how to recover that account  ?
