### ISSUE TITLE
HELP ME !  How To Fix kickout Bot

### ISSUE THREAD

**Issue by alroysh** [carpedm20/LINE#132]
Traceback (most recent call last):
  File "examples/echobot.py", line 33, in <module>
    for op in client.longPoll():
  File "build/bdist.linux-aarch64/egg/line/client.py", line 512, in longPoll
    operations = self._fetchOperations(self.revision, count)
  File "build/bdist.linux-aarch64/egg/line/api.py", line 332, in _fetchOperations
  File "build/bdist.linux-aarch64/egg/curve/CurveThrift.py", line 482, in fetchOperations
  File "build/bdist.linux-aarch64/egg/curve/CurveThrift.py", line 486, in send_fetchOperations
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/thrift/protocol/TCompactProtocol.py", line 140, in writeMessageBegin
    assert self.state == CLEAR
AssertionError

**Comment by fadhiilrachman** [comment]
Line 33 in Assertion was error, maybe you have to learn Python basic

**Comment by alroysh** [comment]
can you help me to fix it?

**Comment by R-N** [comment]
That happened to me too.

Perhaps you're using multithreading? You have to use a lock. Google it.

Else, just reopen the transport, and recall the method.

**Comment by anysz** [comment]
Its happened when thrfit not finish writing the request but you force it to send.
