### ISSUE TITLE
Help me Please

### ISSUE THREAD

**Issue by winlianclub** [carpedm20/LINE#137]
I have this issue and what must i do ??? Help me please... Thanks

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 88, in __init__
    self.login()
  File "line/api.py", line 90, in login
    j = self._get_json(self.LINE_SESSION_NAVER_URL)
  File "line/api.py", line 335, in _get_json
    return json.loads(self._session.get(url, headers=self._headers).text)
  File "/usr/lib/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by sinclairfr** [comment]
check this @ #92

**Comment by winlianclub** [comment]
Now an error like this, please help me

>>> from line import LineClient, LineGroup, LineContact
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/__init__.py", line 11, in <module>
    from .client import LineClient
  File "line/client.py", line 15, in <module>
    from api import LineAPI
  File "line/api.py", line 86
    """Login to LINE server."""

**Comment by merkremont** [comment]
Check my github repo, i have upload new lib.  [_Check here_](https://github.com/merkremont?tab=repositories).
You can use for **free**

**Comment by winlianclub** [comment]
Saya sudah coba sesuai tutorial nya @merkremont tapi masih muncul error

[root@sgx LineVodka]# python vodkabot.py
Traceback (most recent call last):
  File "vodkabot.py", line 2, in <module>
    from LineAlpha import LineClient
  File "/root/LineVodka/LineAlpha/__init__.py", line 3, in <module>
    from .LineApi.LineClient import LineClient
  File "/root/LineVodka/LineAlpha/LineApi/__init__.py", line 3, in <module>
    from .LineClient import LineClient
  File "/root/LineVodka/LineAlpha/LineApi/LineClient.py", line 2, in <module>
    from .LineApi import LineApi
  File "/root/LineVodka/LineAlpha/LineApi/LineApi.py", line 2, in <module>
    import json ,rsa
ImportError: No module named rsa

Tolong petunjuk nya lagi @merkremont :v

**Comment by merkremont** [comment]
@winlianclub
I not Indonesians, please speak English ok.

**Comment by max32002** [comment]
@merkremont thank you very much, bot work again, and I have a new iPad4 now.

```
class Poll:

  client = None

  auth_query_path = "/api/v4/TalkService.do";
  http_query_path = "/S4";
  polling_path = "/P4";
  host = "gd2.line.naver.jp";
  port = 443;

  UA = "Line/6.0.0 iPad4,1 9.0.2"
  LA = "IOSIPAD 6.0.0 iPhone OS 9.0.2"

  rev = 0

  def __init__(self, authToken):
    self.transport = THttpClient.THttpClient(self.host, self.port, self.http_query_path)
    self.transport.setCustomHeaders({
      "User-Agent" : self.UA,
      "X-Line-Application" : self.LA,
      "X-Line-Access": authToken
    });
    self.protocol = TCompactProtocol.TCompactProtocol(self.transport);
    self.client = LineService.Client(self.protocol)
    self.rev = self.client.getLastOpRevision()
    self.transport.path = self.polling_path
    self.transport.open()

```

**Comment by winlianclub** [comment]
@merkremont i want ask you something for your Line Chivas

Why everyone can command Bots at room ??? what must i do ???

May i must to change that's MID ???
admin=["YOUR_MID_HERE"]

What's the mean of "global name 'k3' is not defined" ???

Help me please

**Comment by Ploiiz** [comment]
@merkremont @max32002 
I go to merkremont 's GitHub,but I don't what is lib for download to fixed my bot line.
Presently, I still found internal error when bot line login via old api.
I'm very low skill of develop. Could you please help to explain the solution to resolve as step by step.
Thank you very much.

**Comment by winlianclub** [comment]
@merkremont any issue today like this : 

python chivasbot.py
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "F:\BOTLINE\LineChivas\LineAlpha\LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "F:\BOTLINE\LineChivas\LineAlpha\Api\Talk.py", line 89, in qrLogin
    qr = self.client.getAuthQrcode(True, "Chivas-PC")
  File "F:\BOTLINE\LineChivas\LineAlpha\Gen\LineService.py", line 9273, in getAuthQrcode
    return self.recv_getAuthQrcode()
  File "F:\BOTLINE\LineChivas\LineAlpha\Gen\LineService.py", line 9286, in recv_getAuthQrcode
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line 310, in readMessageBegin
    proto_id = self.__readUByte()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line 289, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "C:\Python27\lib\site-packages\thrift\transport\TTransport.py", line 63, in readAll
    raise EOFError()
EOFError

Help me please

**Comment by anysz** [comment]
@max32002 thos header cant be used rn.

**Comment by Trian03** [comment]
python2 vodkabot.py
Traceback (most recent call last):
  File "vodkabot.py", line 2, in <module>
    from LineAlpha import LineClient
  File "/data/data/com.termux/files/home/LineVodka/LineAlpha/__init__.py", line 3, in <module>
    from .LineApi.LineClient import LineClient
  File "/data/data/com.termux/files/home/LineVodka/LineAlpha/LineApi/__init__.py", line 3, in <module>
    from .LineClient import LineClient
  File "/data/data/com.termux/files/home/LineVodka/LineAlpha/LineApi/LineClient.py", line 2, in <module>
    from .LineApi import LineApi
  File "/data/data/com.termux/files/home/LineVodka/LineAlpha/LineApi/LineApi.py", line 8, in <module>
    from .LineServer import url
  File "/data/data/com.termux/files/home/LineVodka/LineAlpha/LineApi/LineServer.py", line 3, in <module>
    import requests
ImportError: No module named requests

Can you fix this? Or tell me what to do resolve this error

**Comment by Noxturnix** [comment]
Do `pip2 install requests`

**Comment by D-Tri** [comment]
@merkremont why the chivas is always error like this.
please help.
Traceback (most recent call last):
  File "E:\LINEBOT\LineChivas\chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "E:\LINEBOT\LineChivas\LineAlpha\LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "E:\LINEBOT\LineChivas\LineAlpha\Api\Talk.py", line 94, in qrLogin
    "X-Line-Access": qr.verifier,
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): M
exceeded with url: //gd2.line.naver.jp:443/Q (Caused by NewConnectionError('<urll
ion.HTTPConnection object at 0x000000000345DB00>: Failed to establish a new conne
no 11004] getaddrinfo failed',))

**Comment by fpitlok** [comment]
@max32002 do you have UA&LA new?

**Comment by phettest02** [comment]
Can not enter the system. (qr=True)
😩help me

**Comment by lutfi57** [comment]
What is the new LA MAC code ... Please help
