### ISSUE TITLE
I have an error EOF Error

### ISSUE THREAD

**Issue by winlianclub** [carpedm20/LINE#161]
Help me please why i get an error like this today ???

F:\LINEBOT\SBWINLIAN
λ python sbadmin.py
Copy to Line and Click
Your LINK QR is: line://au/q/o8gGKsKJlog5iZFTqiqsWZ0kPau1m4A0
Traceback (most recent call last):
  File "sbadmin.py", line 39, in <module>
    cl.login(qr=True)
  File "F:\LINEBOT\SBWINLIAN\LINETCR\LineApi.py", line 49, in login
    self.Poll = Poll(self.authToken)
  File "F:\LINEBOT\SBWINLIAN\LINETCR\Api\Poll.py", line 35, in __init__
    self.rev = self.client.getLastOpRevision()
  File "F:\LINEBOT\SBWINLIAN\LINETCR\Api\../lib/curve\LineService.py", line 9884, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "F:\LINEBOT\SBWINLIAN\LINETCR\Api\../lib/curve\LineService.py", line 9895, in recv_getLastOpRevision
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line 310, in readMessageBegin
    proto_id = self.__readUByte()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line 289, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "C:\Python27\lib\site-packages\thrift\transport\TTransport.py", line 63, in readAll
    raise EOFError()
EOFError

**Comment by winlianclub** [comment]
How to update line @frostyshield and how to fix it this problem ???

**Comment by Chriskatz** [comment]
Same problem, @frostyshield How to fix this ?

**Comment by SebastienTr** [comment]
Interested by the solution :)
