### ISSUE TITLE
Issue login

### ISSUE THREAD

**Issue by winlianclub** [carpedm20/LINE#165]
Today i found this issue when i want to login

Copy to Line and Click
Your LINK QR is: line://au/q/iOT0HhICL6FxBDhF1hyha8aujzBSGrnp
Traceback (most recent call last):
  File "misael.py", line 40, in <module>
    cl.login(qr=True)
  File "F:\LINEBOT\SBWINLIAN\LINETCR\LineApi.py", line 44, in login
    self.Poll = Poll(self.authToken)
  File "F:\LINEBOT\SBWINLIAN\LINETCR\Api\Poll.py", line 35, in __init__
    self.rev = self.client.getLastOpRevision()
  File "F:\LINEBOT\SBWINLIAN\LINETCR\Api\../lib/curve\LineService.py", line 9884, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "F:\LINEBOT\SBWINLIAN\LINETCR\Api\../lib/curve\LineService.py", line 9907, in recv_getLastOpRevision
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='LOG_OUT', code=8)

How to fix that's ?

**Comment by Sanguarian** [comment]
a lot are seeing this code 8 error, something with the qr login got changed with lines newest update

**Comment by crash-override404** [comment]
fix it if u real programmer lol

**Comment by graspingshiva** [comment]
I am having the same problem.. how do I fix this?

**Comment by Sanguarian** [comment]
How did u get my email?



Sent from my Sprint Samsung Galaxy S7 edge.


-------- Original message --------

**Comment by anysz** [comment]
Server update as always.

**Comment by GraillLord** [comment]
Got the same error :/

**Comment by smarto0o** [comment]
Did someone get solution of this error???
