### ISSUE TITLE
about import LineClient,LineGroup,LineContact

### ISSUE THREAD

**Issue by marconlandita** [carpedm20/LINE#186]
Traceback (most recent call last):
File "", line 1, in 
File "line/init.py", line 11, in 
from .client import LineClient
File "line/client.py", line 86
self.id = id

how to fix this error,and why is this result?

**Comment by marconlandita** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/__init__.py", line 11, in <module>
    from .client import LineClient
  File "line/client.py", line 86
    self.id = id


how to fix this error,and why is this result?

**Comment by Felsaspalt** [comment]
me the same... whyyy

**Comment by ii64** [comment]
You could try mine https://github.com/go-line/linego/releases

Anyway explain in detail, provide error stack or the screenshot.
This repo died due to patch and deprecation RPC function.
