### ISSUE TITLE
EOFError after using ._fetchOperations

### ISSUE THREAD

**Issue by mefirst42** [carpedm20/LINE#28]
i've got this error message after trying to use ._fetchOperations(me.revision,50)

My code snip >>

me = LineClient(authToken='xxxxxxxxxxx')
ops = me._fetchOperations(me.revision,50)
for op in ops:
	if op.type==OT.END_OF_OPERATION:
		pass
	else:
		print "[*] %s" %OT._VALUES_TO_NAMES[op.type]
	me.revision = max(op.revision, me.revision)

Error >>

Traceback (most recent call last):
  File "./LineNotification.py", line 22, in <module>
    ops = me._fetchOperations(me.revision,50)
  File "/usr/local/lib/python2.7/site-packages/line/api.py", line 274, in _fetchOperations
    return self._client.fetchOperations(revision, count)
  File "/usr/local/lib/python2.7/site-packages/curve/CurveThrift.py", line 483, in fetchOperations
    return self.recv_fetchOperations()
  File "/usr/local/lib/python2.7/site-packages/curve/CurveThrift.py", line 495, in recv_fetchOperations
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/usr/local/lib/python2.7/site-packages/thrift/protocol/TCompactProtocol.py", line 310, in readMessageBegin
    proto_id = self.__readUByte()
  File "/usr/local/lib/python2.7/site-packages/thrift/protocol/TCompactProtocol.py", line 289, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/usr/local/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 63, in readAll
    raise EOFError()
EOFError

**Comment by mefirst42** [comment]
i got it

**Comment by R-N** [comment]
I'm also getting EOFErrors. How did you fix this?

**Comment by anysz** [comment]
its client-server error, better find other subserver

**Comment by R-N** [comment]
How do I find existing subservers?

It only happens when fetching operations. For now, I just ignore them all (try-except eof-pass). No operations are being missed so it's good enough, I guess.
