### ISSUE TITLE
invited to no people group

### ISSUE THREAD

**Issue by naari3** [carpedm20/LINE#36]
client.refreshGroups()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/line/client.py", line 148, in refreshGroups
    self.addGroupsWithIds(self._getGroupIdsInvited(), False)
  File "/usr/lib/python2.7/site-packages/line/client.py", line 156, in addGroupsWithIds
    self.groups.append(LineGroup(self, group, is_joined))
  File "/usr/lib/python2.7/site-packages/line/models.py", line 202, in __init__
    for member in group.members:
TypeError: 'NoneType' object is not iterable

**Comment by naari3** [comment]
models.py
~~~~~~~~~~~~~~~~~
def __init__():
~~~~~~~~~~~~~~~~~
        self.members = []
        if group.members:
            for member in group.members:
                self.members.append(LineContact(client, member))

Please consider well

**Comment by carpedm20** [comment]
This is somewhat special case because I can see all of the member list in my accounts. Can you explain details about which group don't display the members well?
