### ISSUE TITLE
Authentication fault exceeded

### ISSUE THREAD

**Issue by mapring0019** [carpedm20/LINE#44]
When i login to LINE, i got a message `Authentication fault exceeded`. Could you tell me what's wrong with my account?

**Comment by zachary822** [comment]
Can you post the stack trace?

**Comment by carpedm20** [comment]
This error is directly related to the login problem which can be a problem of wrong filling of missing codes. Can you share the full error message of this?

**Comment by vichaos** [comment]
I got a same issue 
``` python
>>> from line import LineClient, LineGroup, LineContact
>>> client = LineClient("xxx", "yyy")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 88, in __init__
    self.login()
  File "line/api.py", line 116, in login
    self.com_name, self.provider, self.certificate)
  File "build/bdist.macosx-10.11-intel/egg/curve/CurveThrift.py", line 344, in loginWithIdentityCredentialForCertificate
  File "build/bdist.macosx-10.11-intel/egg/curve/CurveThrift.py", line 375, in recv_loginWithIdentityCredentialForCertificate
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='Authentication fault exceeded', code=4)
```

**Comment by theawangatang** [comment]
Hmmm
