### ISSUE TITLE
JSON ValueError when login

### ISSUE THREAD

**Issue by tribela** [carpedm20/LINE#5]
``` pytb
>>> import line
>>> client = line.LineClient('<ID>', '<password>')
Enter PinCode 'None' to your mobile phone in 2 minutes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 78, in __init__
    self.login()
  File "line/api.py", line 91, in login
    j = self._get_json(self.LINE_CERTIFICATE_URL)
  File "line/api.py", line 250, in _get_json
    return json.loads(self._session.get(url, headers=self._headers).text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by abcd476555** [comment]
My code is just below:
from line import LineClient, LineGroup, LineContact
client = LineClient(authToken="...about 87 lenght....")

I also got this error:
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='AUTHENTICAT
ION_DIVESTED_BY_OTHER_DEVICE', code=8)

I'm already quit LINE Windows but still got error, please guide me how you solve this.

**Comment by carpedm20** [comment]
Based on this code https://github.com/devunt/purple-line/blob/master/linehttptransport.cpp#L245, which is another LINE python library, the author of this code said your error is occurred because `you logged in from another device.`

Hmm.. how about trying to login with LINE windows again and logout, and then login with `LineClient`?

**Comment by cslinmiso** [comment]
I've met this problem before, it was because the token is in some way 'invaild', since it was used to log in before you get the chance to log in with it. Try to log it out with your mobile device. it should be in Settings....can't remember exact name for it.

**Comment by CyberTKR** [comment]
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='REVOKE', code=8) 

Help Me Please..

**Comment by djruiayng** [comment]
$ python3 war.py


Traceback (most recent call last):
  File "war.py", line 18, in <module>
    line = LINE("EJuYwmWfEUX3adxRvcP5.Z8DeyMFRPhJA0JZec/GGrq.0Z8+OghH33V1xR5vItyGQhuYqNIqmH5niyXaV9S0SPk=")
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/linepy/client.py", line 21, in __init__
    self.loginWithAuthToken(authToken=idOrAuthToken, appName=appName)
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/linepy/auth.py", line 193, in loginWithAuthToken
    self.__loadSession()
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/linepy/auth.py", line 31, in __loadSession
    self.revision = self.poll.getLastOpRevision()
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/akad/TalkService.py", line 4432, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/akad/TalkService.py", line 4455, in recv_getLastOpRevision
    raise result.e
Dhenza7.akad.ttypes.TalkException: TalkException(code=8, reason='AUTHENTICATION_DIVESTED_BY_OTHER_DEVICE', parameterMap=None)
======================================================
Who can save me? I am stuck here.
