### ISSUE TITLE
Login Failed 

### ISSUE THREAD

**Issue by isairz** [carpedm20/LINE#57]
I have used this library from last year, but suddenly this occur login error at login.

```
Traceback (most recent call last):
  File "token.py", line 2, in <module>
    client = LineClient("emailid@naver.com", "password")
  File "/home/isair/private/LINE/line/client.py", line 88, in __init__
    self.login()
  File "/home/isair/private/LINE/line/api.py", line 101, in login
    j = self._get_json(self.LINE_SESSION_LINE_URL)
  File "/home/isair/private/LINE/line/api.py", line 348, in _get_json
    return json.loads(self._session.get(url, headers=self._headers).text)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by vijay32** [comment]
Same issue here. I just logged in once. It worked, but unable to login again after running the script again.
