### ISSUE TITLE
REVOKE Access while login using authentication token

### ISSUE THREAD

**Issue by kslweb** [carpedm20/LINE#66]
So i got this error when i try to login with authentication token. The error showing up like this :

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 321, in __init__
    self.revision = self._getLastOpRevision()
  File "line/client.py", line 609, in _getLastOpRevision
    return self._client.getLastOpRevision()
  File "/Library/Python/2.7/site-packages/curve/CurveThrift.py", line 512, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/Library/Python/2.7/site-packages/curve/CurveThrift.py", line 534, in recv_getLastOpRevision
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='REVOKE', code=8)
```
Do you know how to handle this error message? Thanks in advance.

**Comment by AndyAng1991** [comment]
did you get the right one authtoken?maybe you need run as administrator for the python IDE you currently using.. 

On the side note, did you install Apache Thrift correctly?
