### ISSUE TITLE
Got nothing at getRecentMessages()

### ISSUE THREAD

**Issue by s0rt** [carpedm20/LINE#74]
> messages = friend.getRecentMessages(count=10)
   print messages

>

>

The output should be like this:

> [LineMessage (contentType=NONE, sender=None, receiver=<LineContact 파랑봇>, msg="hello World!")]

>

>

But the output is:

> []

>

>

There's nothing inside "[]" things

**Comment by pinfort** [comment]
Me too.

**Comment by royl2k90** [comment]
Same here. Type the following in Python command line...

`from line import LineClient`
`client = LineClient("your_email", "your_password")`
`client = LineClient(authToken=client.authToken)`
`client.updateAuthToken()`

Do you get exception error: you need to login first because there is no valid certificate?

I am not sure if having the certificate would display the recent messages sent by friends. What do you think?

**Comment by jackzett** [comment]
I got the same issue but...
exception error: you need to login first because there is no valid certificate?
Can be fixed by deleting .line.crt and loging in using the (id, pass)

**Comment by s0rt** [comment]
I think I dont have any issue about the certificate.
It's just can't read the message.
It works when I send a message, but can't read the message.

**Comment by anusoft** [comment]
I think it's letter sealing, turn it off and you may see the message.

**Comment by jackzett** [comment]
True you can try disabling letter sealing on your bot account on phone
Settings > Chats & Voice Calls > Letter sealing 
Didnt work for me though, no matter how many times i login , update authtoken or anything
I still cant read messages somehow

**Comment by asdqwe3124** [comment]
still can't read messages even though letter sealing disabled.

**Comment by LieAlbertTriAdrian** [comment]
I got nothing as well in getRecentMessages. What happened?

**Comment by anysz** [comment]
Seriously.. Letter-Sealing(SSL) is annoy even its turned off(disabled) its doesnt allow you to read any messages!.i think since August 10, 2016

**Comment by anythingg** [comment]
ok I turned off letter sealing. How do I use long Poll to get messages?

**Comment by anysz** [comment]
the example.py had example how to use longPoll

**Comment by anythingg** [comment]
i dont see an example.py but i found an echobot.py inside of the examples folder which has longPoll.
if I run the script after modifying it with my authToken and certificate then i get an error because of the line receiver.sendMessage("[%s] %s" % (sender.name, msg))

the error i get is this

jin@jins-pc:~/LINE$ python decepticon-_client.py
login successful
Traceback (most recent call last):
  File "decepticon-_client.py", line 21, in <module>
    receiver.sendMessage("[%s] %s" % (sender.name, msg))
  File "/home/jin/LINE/line/models.py", line 68, in sendMessage
    raise e
AttributeError: 'LineClient' object has no attribute 'provider'


and when I change        receiver.sendMessage("[%s] %s" % (sender.name, msg))    to    message.sendMessage("[%s] %s" % (sender.name, msg))    i get this error

jin@jins-pc:~/LINE$ python decepticon-_client.py
login successful
Traceback (most recent call last):
  File "decepticon-_client.py", line 21, in <module>
    message.sendMessage("[%s] %s" % (sender.name, msg))
AttributeError: LineMessage instance has no attribute 'sendMessage'


if i change it to sender.sendMessage(msg)
i don't get any errors and the script works like normal
why wont receiver and message work? how do i get them to work?

**Comment by anysz** [comment]
its looks like something missing cuz 
`AttributeError: 'LineClient' object has no attribute 'provider'`
or you was edit something

**Comment by anythingg** [comment]
i tried with the default carpedm20 client.py but still get that error. 

client.py
https://pastebin.com/80MGcmZK

**Comment by anythingg** [comment]
Can someone please help me?
