### ISSUE TITLE
Help me!!!

### ISSUE THREAD

**Issue by craftalpian** [carpedm20/LINE#79]
Traceback (most recent call last):
  File "C:\Users\Fikar-PC\Documents\LINE-master\line\bot.py", line 24, in <module>
    receiver.sendMessage('[%s] %s' % (sender.name, msg))
  File "build\bdist.win32\egg\line\models.py", line 68, in sendMessage
    raise e
Exception: Error: You need to login first. There is no valid certificate

**Comment by anysz** [comment]
This seems like you had a problem with LINE api.

**Comment by C109110136** [comment]
People
