### ISSUE TITLE
Line deactivates account

### ISSUE THREAD

**Issue by tmjvonboss** [carpedm20/LINE#83]

**Comment by crazy-ace003** [comment]
Im facing the issue too. When I don't expect the login, i get this error:
This sucks. Hopefully someone can get a workaround. Like most of the bots mine was used for a useful non destructive use. :(
Traceback (most recent call last):
  File "listen.py", line 20, in <module>
    client = LineClient("i@gmail.com", "")
  File "build/bdist.linux-x86_64/egg/line/client.py", line 88, in __init__
  File "build/bdist.linux-x86_64/egg/line/api.py", line 130, in login
  File "/usr/local/lib/python2.7/dist-packages/curve/CurveThrift.py", line 344, in loginWithIdentityCredentialForCertificate
    return self.recv_loginWithIdentityCredentialForCertificate()
  File "/usr/local/lib/python2.7/dist-packages/curve/CurveThrift.py", line 375, in recv_loginWithIdentityCredentialForCertificate
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason="Account is deactivated because it's not bound to any primary device", code=22)

**Comment by ivan98** [comment]
Same here; "Account is deactivated because it's not bound to any primary device", code=22.

I've tried reducing my rate of interaction with LINE, but to little effect, if any. I've turned on full debug, and am now investigating "fetchOperations" returning "HTTP 410 Gone" status.

"fetchOperations" normally returns every 110 secs with HTTP 200 status code, but when I see 410 returns for a while, then it craps out with "Account is deactivated because it's not bound to any primary device", code=22.

**Comment by Colonel-Top** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\line\client.py", line 88, in __init__
    self.login()
  File "build\bdist.win32\egg\line\api.py", line 130, in login
    self.com_name, self.provider, self.certificate)
  File "build\bdist.win32\egg\curve\CurveThrift.py", line 344, in loginWithIdent
ityCredentialForCertificate
  File "build\bdist.win32\egg\curve\CurveThrift.py", line 375, in recv_loginWith
IdentityCredentialForCertificate
curve.ttypes.TalkException: TalkException(parameterMap=None, reason="Account is
deactivated because it's not bound to any primary device", code=22)
same here

**Comment by max32002** [comment]
What's the different in network package between official client and non-official client(LINE BOT)? How to get the latest client version on Mac?

**Comment by anusoft** [comment]
You can use Official Messaging API for now, the downside is there's no join/leave event for people in group and there's no storage for image/video/sound and text characters limit to 2,000.


https://business.line.me/en/services/bot

**Comment by max32002** [comment]
Official and non-released project only for developer use only, LINE company has too many reasons to reject our submit request. There are too many limitations on Official Messaging API, and Official version unable to query a LINE ID info.

**Comment by i98derKrampus** [comment]
First keep getting a TalkException in longPoll (reason = "REVOKE", code = NOT_AUTHORIZED_DEVICE)
and then when I try to relogin get the same TalkException as you (reason = "Account is deactivated because it's not bound to any primary device", code = DEACTIVATED_ACCOUNT_BOUND_TO_THIS_IDENTITY)
and have to relogin on the android device.
Updating the request URLs didn't help, nor did replacing fetchOperations() with the function used by Android devices

**Comment by infinitylabs** [comment]
same error. seems to happen at random and not based on use/messaging.

**Comment by max32002** [comment]
after REVOKE, new server side message is: **None**

>   File "/line-0.8.0/line/client.py", line 91, in __init__
>     self.revision = self._getLastOpRevision()
>   File "/line-0.8.0/line/api.py", line 330, in _getLastOpRevision
>     return self._client.getLastOpRevision()
>   File "/line-0.8.0/line/curve/CurveThrift.py", line 519, in getLastOpRevision
>     return self.recv_getLastOpRevision()
>   File "/line-0.8.0/line/curve/CurveThrift.py", line 541, in recv_getLastOpRevision
>     raise result.e
> line.curve.ttypes.TalkException: TalkException(parameterMap=None, reason=None, code=20)

**Comment by anysz** [comment]
After You logged in your account on device, it should be run as well. (Back active)

**Comment by katro9999** [comment]
TalkException(parameterMap=None, reason='LOG_OUT', code=8)

I got this error,who can help ke solved this error

**Comment by CyberTKR** [comment]
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='REVOKE', code=8)

Help ..
