### ISSUE TITLE
No JSON object could be decoded!  help!

### ISSUE THREAD

**Issue by chungsir** [carpedm20/LINE#92]
File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by max32002** [comment]
self._headers['X-Line-Application'] cause LINE server response empty when call to LINE_DOMAIN = "http://gd2.line.naver.jp".

**Comment by chungsir** [comment]
now can't login in to get lineclient
how to modify it 
thanks very much

**Comment by seltun** [comment]
Also having this issue, was anyone able to find the solution?

**Comment by max32002** [comment]
in the def login(self): in api.py
        self._headers['X-Line-Application']=app
        self.transport.setCustomHeaders(self._headers)

shinomura: now I can login and get authtoken
> 1.disable header "X-Line-Application" before get json
> 2.add it back after that then change LINE_DOMAIN from http to https

**Comment by Ploiiz** [comment]
Hi max32002, I have any question, could you please help to confirm.

1.disable header "X-Line-Application" before get json
Question#1: Above header for disable that is it mean to mark or remove only line as "self._headers['X-Line-Application']=app" in api.py , right?

Question#2: If correct, the next step after disable header - Is it compile bot line code as once time before implement activity 2.,right?

2.add it back after that then change LINE_DOMAIN from http to https
Question#3: The next step is adding the header of 'self._headers['X-Line-Application']=app' and change to https. And then compile bot line code again, right?

Thank you very much

**Comment by max32002** [comment]
in api.py, change http to https:
```
class LineAPI(object):
    """This class is a wrapper of LINE API

    """
    LINE_DOMAIN = "https://gd2.line.naver.jp"

```

----

```
    def login(self):
        """Login to LINE server."""
        if self.provider == CurveThrift.Provider.LINE: # LINE
            j = self._get_json(self.LINE_SESSION_LINE_URL)
        else: # NAVER
            j = self._get_json(self.LINE_SESSION_NAVER_URL)

        session_key = j['session_key']
        message     = (chr(len(session_key)) + session_key +
                       chr(len(self.id)) + self.id +
                       chr(len(self.password)) + self.password).encode('utf-8')

        keyname, n, e = j['rsa_key'].split(",")
        pub_key       = rsa.PublicKey(int(n,16), int(e,16))
        crypto        = rsa.encrypt(message, pub_key).encode('hex')

        self.transport = THttpClient.THttpClient(self.LINE_HTTP_URL)
        os_version = "10.9.4-MAVERICKS-x64"
        app = "DESKTOPMAC\t%s\tMAC\t%s" % (self.version, os_version)
        self._headers['X-Line-Application']=app

```

**Comment by brendhadhea** [comment]
I've done that but I get this
TypeError: 'unicode' does not have the buffer interface

**Comment by anysz** [comment]
use thrift v0.9.3

**Comment by Ploiiz** [comment]
Hi Max,

Today, I change LINE_DOMAIN to "https://gd2.line.naver.jp" that I can login
successful.
But I can send only text message. Then, image message was failed to send.
I receive an error "Send image fail Line group is not exist" although I
send text message to the same group.
Cloud you please help to advise.
Thank you very much


[2017-05-11 18:46:52.832244] [test@gmail.com] [Initial] Start login line
client
[2017-05-11 18:46:57.620598] [test@gmail.com] [Initial] Login Success
[2017-05-11 18:46:57.620689] [Login] [test@gmail.com] -
AuthToken=Egvn8eLkB8vEA64yilpf.UzPg4X6oF73wMIC8vfve3W.RTBbJyGkfrw+oOM6/Q7DDp78e4Pqf+D7ImwCoqBu33k=
[2017-05-11 18:46:57.624577] [test@gmail.com] [Initial] Establish socket
listener on port 8090
[2017-05-11 18:47:37.690681] [test@gmail.com] [Socket] [ip:port] Send text
success - Group(Tester) : pp
[2017-05-11 18:47:59.835257] [test@gmail.com] [Socket] [ip:port] Send image
fail Line group is not exist - Group(Tester) : Size 27087 bytes

2017-03-15 17:32 GMT+07:00 Max <notifications@github.com>:

**Comment by Nilpo** [comment]
Resolved in #93

**Comment by anoaghost** [comment]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 93, in __init__
    self.login()
  File "line/api.py", line 158, in login

  File "/usr/local/lib/python2.7/dist-packages/curve/CurveThrift.py", line 343, in loginWithIdentityCredentialForCertificate
    self.send_loginWithIdentityCredentialForCertificate(identifier, password, keyname, crypto, keepLoggedIn, accessLocation, systemName, identityProvider, certificate)
  File "/usr/local/lib/python2.7/dist-packages/curve/CurveThrift.py", line 358, in send_loginWithIdentityCredentialForCertificate
    args.write(self._oprot)
  File "/usr/local/lib/python2.7/dist-packages/curve/CurveThrift.py", line 2416, in write
    oprot.writeString(self.keyname)
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TProtocol.py", line 121, in writeString
    self.writeBinary(str_to_binary(str_val))
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TCompactProtocol.py", line 42, in nested
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TCompactProtocol.py", line 272, in __writeBinary
    self.trans.write(s)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/THttpClient.py", line 134, in write
    self.__wbuf.write(buf)
TypeError: 'unicode' does not have the buffer interface`

i try , like this, who's can solved it ?

**Comment by Nilpo** [comment]
Please read the comment before you. This is resolved in #93

**Comment by RichoDS** [comment]
![wqe](https://cloud.githubusercontent.com/assets/29066224/26595550/a3baded8-4520-11e7-856a-f2bd8cac1096.png)


please help me!

**Comment by Nilpo** [comment]
Please read the comments.

**Comment by RichoDS** [comment]
I am confused..
I'm a beginner..

**Comment by Ploiiz** [comment]
Hi' Max,

I have some problem today.
I found an error as following:-

[2017-08-01 16:33:41.259085] [Login] [AM-[Official]] - Start login line
client
[2017-08-01 16:33:42.054822] [Login] [AM-[Official]] - Login Fail
[2017-08-01 16:33:42.054933] [Error exception in main thread]
TalkException(parameterMap=None, reason='Internal error', code=20)

How I can resolve about 'Internal error'?

Thank you so much.

2017-03-15 17:32 GMT+07:00 Max <notifications@github.com>:

**Comment by R-N** [comment]
@Ploiiz Line updated something so it doesn't work
#131

**Comment by Ploiiz** [comment]
Oh, If you have solution for resole that, could you please help to inform
me.
Thank you.

2017-08-02 18:55 GMT+07:00 Muhammad Rizqi Nur <notifications@github.com>:
